language: node_js
node_js:
  - "10.12.0"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - npm i
  - node index.js & export APP_ID=$!
  - sleep 1

script:
  - node_modules/.bin/newman run postman_unittests/db.json
  - node_modules/.bin/newman run postman_unittests/accounts.json
  - node_modules/.bin/newman run postman_unittests/boleia.json
  - kill -9 $APP_ID